shift tab

diff --git a/abf b/abf
--- a/abf
+++ b/abf
@@ -11,52 +11,52 @@ for sys_dir in $(package-query -Sf "%F" filesystem); do
 done
 
 build_pkgs() { repo_name=$1 ; arch=$2 ; packages=$3
-		echo "Building packages ($packages) for ${repo_name} (${arch})..."
-		tmp_abf=/tmp/abf && mkdir -p $tmp_abf
-		repo_out=$(mktemp --tmpdir=${tmp_abf} -d abf.build.${repo_name}.$arch.XXX)
-		repo_root=$VAR_DIR/repo
-		repo_dest=$repo_root/$repo_name
+	echo "Building packages ($packages) for ${repo_name} (${arch})..."
+	tmp_abf=/tmp/abf && mkdir -p $tmp_abf
+	repo_out=$(mktemp --tmpdir=${tmp_abf} -d abf.build.${repo_name}.$arch.XXX)
+	repo_root=$VAR_DIR/repo
+	repo_dest=$repo_root/$repo_name
 
-		[[ -w $repo_root ]] || { echo "ERROR: $repo_root must be writable."; exit; }
-		[[ -d ${repo_dest}/any ]] || mkdir -p ${repo_dest}/any
-		[[ -d ${repo_dest}/$arch ]] || mkdir -p ${repo_dest}/$arch
+	[[ -w $repo_root ]] || { echo "ERROR: $repo_root must be writable."; exit; }
+	[[ -d ${repo_dest}/any ]] || mkdir -p ${repo_dest}/any
+	[[ -d ${repo_dest}/$arch ]] || mkdir -p ${repo_dest}/$arch
 
-		schroot -c abf-$arch -d /tmp -u root -- yaourt --export ${repo_out} --noconfirm -S ${packages}
+	schroot -c abf-$arch -d /tmp -u root -- yaourt --export ${repo_out} --noconfirm -S ${packages}
 
-		find ${repo_out} -name '*.pkg.tar.*' -printf "%f %p\n" | \
-		while read pkg_file pkg_path; do
-			read pkg_name pkg_ver pkg_arch <<< $(package-query -f "%n %v %a" -p $pkg_path)
+	find ${repo_out} -name '*.pkg.tar.*' -printf "%f %p\n" | \
+	while read pkg_file pkg_path; do
+		read pkg_name pkg_ver pkg_arch <<< $(package-query -f "%n %v %a" -p $pkg_path)
 
-			pkg_conf=$REPO_CONF/$repo_name/$pkg_name
-			pkg_dest=${repo_dest}/$arch/$pkg_file
-			pkg_dest_any=${repo_dest}/any/$pkg_file
-			repo_db=${repo_dest}/$arch/${repo_name}.db.tar.gz
+		pkg_conf=$REPO_CONF/$repo_name/$pkg_name
+		pkg_dest=${repo_dest}/$arch/$pkg_file
+		pkg_dest_any=${repo_dest}/any/$pkg_file
+		repo_db=${repo_dest}/$arch/${repo_name}.db.tar.gz
 
-			if [[ $pkg_arch == 'any' ]]; then
-				if [[ $(stat -c '%Y' $pkg_dest_any) == $(stat -c '%Y' $pkg_conf) ]]; then
-					echo "Skipping $pkg_name in ${repo_name} (any) repository... "
-					rm ${pkg_path}
-				else
-					echo "Moving $pkg_name to ${repo_name} (any) repository... "
-					mv $pkg_path $pkg_dest_any
-				fi
-				ln -sf ../any/$pkg_file $pkg_dest
+		if [[ $pkg_arch == 'any' ]]; then
+			if [[ $(stat -c '%Y' $pkg_dest_any) == $(stat -c '%Y' $pkg_conf) ]]; then
+				echo "Skipping $pkg_name in ${repo_name} (any) repository... "
+				rm ${pkg_path}
 			else
-				echo "Moving $pkg_name to ${repo_name} ($arch) repository... "
-				mv -f $pkg_path $pkg_dest
+				echo "Moving $pkg_name to ${repo_name} (any) repository... "
+				mv $pkg_path $pkg_dest_any
 			fi
-			
-			if [ -f $pkg_dest ]; then
-				touch $pkg_conf
-				touch -hc -r $pkg_conf $repo_dest/*/$pkg_name-$pkg_ver-*.pkg.tar.xz
-				echo "Adding $pkg_name to ${repo_name} database... "
-				repo-add -f -d $repo_db $pkg_dest || \
-					echo "Failed to add $pkg_name to $repo_name"
-			fi
-		done
+			ln -sf ../any/$pkg_file $pkg_dest
+		else
+			echo "Moving $pkg_name to ${repo_name} ($arch) repository... "
+			mv -f $pkg_path $pkg_dest
+		fi
+		
+		if [ -f $pkg_dest ]; then
+			touch $pkg_conf
+			touch -hc -r $pkg_conf $repo_dest/*/$pkg_name-$pkg_ver-*.pkg.tar.xz
+			echo "Adding $pkg_name to ${repo_name} database... "
+			repo-add -f -d $repo_db $pkg_dest || \
+				echo "Failed to add $pkg_name to $repo_name"
+		fi
+	done
 
-		rm -rf $repo_out
-		rm -rf $tmp_abf
+	rm -rf $repo_out
+	rm -rf $tmp_abf
 }
 
 get_stale_pkgs() {
